### ISSUE TITLE
Add objectSpec

### ISSUE THREAD

**Issue by markovip** [simenkid/lwm2m-id#4]
Hi guys,
since there is a way to extend default object and resource definitions with `addOid()`, `addRid()`, `addSpecificRid(),` etc., I've noticed that objectSpec cannot be added.

I'd like to extend **apnConnProfile** object definition, i.e.:

`{
    "specificRid": {
        "apnConnProfile": {
            "profileName": 0,
            "APN": 1,
            "authenticationType": 4,
            "username": 5,
            "secret": 6,
            "ipAddress": 15
        }
    },
    "objectSpec": {
        "apnConnProfile": { "multi": true, "mand": false }
    },
    "specificResrcChar": {
        "apnConnProfile": {
            "profileName": { "access": "RW", "multi": false, "mand": true, "type": "string", "range": null, "init": "" },
            "APN": { "access": "RW", "multi": false, "mand": false, "type": "string", "range": null, "init": "" },
            "authenticationType": { "access": null, "multi": false, "mand": true, "type": "integer", "range": [0, 1, 2, 3], "init": 0 },
            "username": { "access": null, "multi": false, "mand": false, "type": "string", "range": null, "init": "" },
            "secret": { "access": null, "multi": false, "mand": false, "type": "string", "range": null, "init": "" },
            "ipAddress": { "access": null, "multi": true, "mand": false, "type": "string", "range": null, "init": "" }
        }
    }
}`

Adding specificRid and specificResrcChar works like a charm, but there's no way to add objectSpec, something like:
`DEFS.addObjectSpec = function(oid, items)`

Regards,
Marko.

**Comment by simenkid** [comment]
Hi @markovip. I've added a new method `addObjectSpec(oid, items)` to v1.6.4, please have a try.

**Comment by markovip** [comment]
Hi @simenkid ,
Again it works like a charm. Closing the issue.
Thx.
